{% set name = "sqlmesh" %}
{% set version = "0.210.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlmesh-{{ version }}.tar.gz
  sha256: 5cd98d262661dc893b8144511a6a3c87c5d35ceb045458303c3e21e303172409

build:
  noarch: python
  entry_points:
    - sqlmesh = sqlmesh.cli.main:cli
    - sqlmesh_cicd = sqlmesh.cicd.bot:bot
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python-dotenv
    - python >={{ python_min }}
    - astor
    - click
    - croniter
    - python-duckdb >=0.10.0,!=0.10.3
    - dateparser <=1.2.1
    - hyperscript >=0.1.0
    - importlib-metadata
    - ipywidgets
    - jinja2
    - packaging
    - pandas
    - pydantic >=2.0.0
    - requests
    - rich
    - ruamel.yaml
    - sqlglot >=27.8.0,<27.9.dev0
    - tenacity
    - time-machine
    - json_stream

test:
  imports:
    - sqlmesh
    - web
  commands:
    - pip check
    - sqlmesh --help
    - sqlmesh_cicd --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/TobikoData/sqlmesh
  summary: Efficient data transformation and modeling framework that is backwards compatible with dbt.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - fhoehle
