{% set name = "sqlmesh" %}
{% set version = "0.142.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlmesh-{{ version }}.tar.gz
  sha256: 31d7a8099f2b8c98b291f224520809b52a3b0aca5e372ed9207f858dd46d4c4e

build:
  noarch: python
  entry_points:
    - sqlmesh = sqlmesh.cli.main:cli
    - sqlmesh_cicd = sqlmesh.cicd.bot:bot
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - time-machine
    - python >={{ python_min }}
    - astor
    - click
    - croniter
    - python-duckdb !=0.10.3
    - dateparser
    - freezegun
    - hyperscript >=0.1.0
    - importlib-metadata
    - ipywidgets
    - jinja2
    - pandas
    - pydantic >=2.0.0
    - requests
    - rich
    - ruamel.yaml
    - sqlglot >=26.0.1,<26.1.dev0
    # https://github.com/TobikoData/sqlmesh/blob/main/setup.py#L50
    #   "sqlglot[rs]~=25.31.4"
    # https://github.com/tobymao/sqlglot/blob/main/CHANGELOG.md
    # https://github.com/tobymao/sqlglot/blob/v25.32.1/sqlglotrs/Cargo.toml
    - sqlglotrs >=0.3.0
    - tenacity

test:
  imports:
    - sqlmesh
    - web
  commands:
    - pip check
    - sqlmesh --help
    - sqlmesh_cicd --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/TobikoData/sqlmesh
  summary: Efficient data transformation and modeling framework that is backwards compatible with dbt.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
