{% set name = "sqlmesh" %}
{% set version = "0.129.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlmesh-{{ version }}.tar.gz
  sha256: 0d04147be13591c51fac4c2fb51b9885a1a523e0a75e1ee4415076f746444c77

build:
  noarch: python
  entry_points:
    - sqlmesh = sqlmesh.cli.main:cli
    - sqlmesh_cicd = sqlmesh.cicd.bot:bot
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - astor
    - click
    - croniter
    - python-duckdb !=0.10.3
    - dateparser
    - freezegun
    - hyperscript >=0.1.0
    - importlib-metadata
    - ipywidgets
    - jinja2
    - pandas
    - pydantic
    - requests
    - rich
    - ruamel.yaml
    - sqlglot >=25.20.1,<25.21
    - tenacity
  run_constrained:
    - sqlglotrs >=0.2.12

test:
  imports:
    - sqlmesh
    - web
  commands:
    - pip check
    - sqlmesh --help
    - sqlmesh_cicd --help
  requires:
    - pip

about:
  home: https://github.com/TobikoData/sqlmesh
  summary: Efficient data transformation and modeling framework that is backwards compatible with dbt.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
