# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: sqlmesh
  version: "0.196.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sqlmesh-${{ version }}.tar.gz
  sha256: e09bed5024451cbdaa0de4081e29f8a1b526363d5bb37c75fa3b54e03d2cdbca

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sqlmesh = sqlmesh.cli.main:cli
      - sqlmesh_cicd = sqlmesh.cicd.bot:bot
      - sqlmesh_lsp = sqlmesh.lsp.main:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - setuptools-scm
    - toml
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - astor
    - click
    - croniter
    - python-duckdb >=0.10.0,!=0.10.3
    - dateparser
    - hyperscript >=0.1.0
    - importlib-metadata
    - ipywidgets
    - jinja2
    - packaging
    - pandas
    - pydantic >=2.0.0
    - requests
    - rich
    - ruamel.yaml
    - sqlglot >=26.30.0,<26.31.dev0
    - tenacity
    - time-machine
    - json_stream

tests:
  - python:
      imports:
        - sqlmesh
        - web
      pip_check: true
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - sqlmesh --help
      - sqlmesh_cicd --help
      - sqlmesh_lsp --help

about:
  homepage: https://github.com/TobikoData/sqlmes
  summary: Next-generation data transformation framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - fhoehle
